"""empty message

Revision ID: 13af3552d2b0
Revises: bacb0b5787fd
Create Date: 2017-10-18 16:53:17.227218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13af3552d2b0'
down_revision = 'bacb0b5787fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullName', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_users_fullName'), 'users', ['fullName'], unique=False)
    op.drop_index('ix_users_full_name', table_name='users')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', mysql.VARCHAR(length=60), nullable=True))
    op.create_index('ix_users_full_name', 'users', ['full_name'], unique=False)
    op.drop_index(op.f('ix_users_fullName'), table_name='users')
    op.drop_column('users', 'fullName')
    # ### end Alembic commands ###
