"""empty message

Revision ID: 94c396a079a7
Revises: 84cebdce5df3
Create Date: 2017-10-17 02:33:48.880160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94c396a079a7'
down_revision = '84cebdce5df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.drop_index('ix_users_fullName', table_name='users')
    op.drop_column('users', 'fullName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fullName', mysql.VARCHAR(length=60), nullable=True))
    op.create_index('ix_users_fullName', 'users', ['fullName'], unique=False)
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
