"""empty message

Revision ID: bacb0b5787fd
Revises: 94c396a079a7
Create Date: 2017-10-17 21:15:39.398194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacb0b5787fd'
down_revision = '94c396a079a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('access', table_name='documents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('access', 'documents', ['access'], unique=True)
    # ### end Alembic commands ###
